# Generated by Django 4.2 on 2023-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('source', models.URLField()),
            ],
        ),
    ]
